topics:
- name    : lidar_obstacle_emergency
  topic   : emergency/cmd_vel
  timeout : 0.5
  priority: 14
- name    : joy
  topic   : joyvel/cmd_vel
  timeout : 0.5
  priority: 10
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
